using System;
using System.Numerics;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Diagnostics;

namespace projectEuler27
{
    class Program
    {
        static void Main(string[] args)
        {
            new Program().callMe();
        }

        int[] primes;
        private void callMe()
        {
            Stopwatch clock = Stopwatch.StartNew();

            int aMax = 0, bMax = 0, nMax = 0;
            primes = ESieve(87400);

            for (int a = -1000; a <= 1000; a++)
            {
                for (int b = -1000; b <= 1000; b++)
                {

                    int n = 0;
                    while (isPrime(Math.Abs(n * n + a * n + b)))
                    {
                        n++;
                    }

                    if (n > nMax)
                    {
                        aMax = a;
                        bMax = b;
                        nMax = n;
                    }
                }
            }

            clock.Stop();
            Console.WriteLine("A sequence of length {0}, is generated by a={1}, b={2}, the product is {3}", nMax, aMax, bMax, aMax * bMax);
            Console.WriteLine("Solution took {0} ms", clock.ElapsedMilliseconds);
        }
        private bool isPrime(int testNumber)
        {
            int i = 0;
            while (primes[i] <= testNumber)
            {
                if (primes[i] == testNumber)
                {
                    return true;
                }
                i++;
            }
            return false;
        }

        public int[] ESieve(int upperLimit)
        {
            int sieveBound = (int)(upperLimit - 1) / 2;
            int upperSqrt = ((int)Math.Sqrt(upperLimit) - 1) / 2;

            BitArray PrimeBits = new BitArray(sieveBound + 1, true);

            for (int i = 1; i <= upperSqrt; i++)
            {
                if (PrimeBits.Get(i))
                {
                    for (int j = i * 2 * (i + 1); j <= sieveBound; j += 2 * i + 1)
                    {
                        PrimeBits.Set(j, false);
                    }
                }
            }

            List<int> numbers = new List<int>((int)(upperLimit / (Math.Log(upperLimit) - 1.08366)));
            numbers.Add(2);

            for (int i = 1; i <= sieveBound; i++)
            {
                if (PrimeBits.Get(i))
                {
                    numbers.Add(2 * i + 1);
                }
            }

            return numbers.ToArray();
        }
    }
}
